export default {
  FACEBOOK_ID: "",
  TWITTER_ID: "",
  INSTAGRAM_ID: "",
  SPOTIFY_ID: "",
  LINKEDIN_ID: "ali4heydari",
  TWITCH_ID: "ali4heydari",
  BIRTHDATE: new Date(1997, 0, 30),
  CALENDLY_EVENT_LINK: "15min",
  CALENDLY_ID: "ali4heydari",
  CONTACT_EMAIL: "ali4heydari+githubio@gmail.com",
  CONTACT_PHONE: "+98 936 856 3509",
  SHORT_NAME: "Ali Heydari's personal website",
  SITE_TITLE: "Ali Heydari",
  SITE_DESCRIPTION: "Ali Heydari's personal website",
  SITE_AUTHOR: "Ali Heydari",
  GITHUB_ID: "ali4heydari",
  GITLAB_ID: "ali4heydari",
  STACK_OVER_FLOW_ID: "8777320/ali4heydari",
  SKYPE_INVITE_ID: "lo1ReeemgPvq",
  SLIDES_ID: "ali4heydari",
  CONTACT_GET_FORM_ID: "b721c787-7978-40ec-9253-5fefaaa6d1e0",
  DISCORD_SERVER_ID: "7Z4Wk2zUuj",
};
