export default {
  FACEBOOK_ID: "",
  TWITTER_ID: "",
  INSTAGRAM_ID: "ali4heydari",
  LINKEDIN_ID: "ali4heydari",
  CALENDLY_ID: "ali4heydari/15min",
  CONTACT_EMAIL: "ali4heydari+githubio@gmail.com",
  CONTACT_PHONE: "+98 936 856 3509",
  SHORT_NAME: "Ali Heydari's protfolio",
  SITE_TITLE: "Ali Heydari",
  SITE_DESCRIPTION: "Ali Heydari's protfolio",
  SITE_AUTHOR: "Ali Heydari",
  GITHUB_ID: "ali4heydari",
  GITLAB_ID: "ali4heydari",
  STACK_OVER_FLOW_ID: "8777320/ali4heydari",
};
