const siteConfig = {
  FACEBOOK_ID: "",
  TWITTER_ID: "",
  INSTAGRAM_ID: "",
  SPOTIFY_ID: "ali4heydari",
  STEAM_ID: "ali4heydari",
  LINKEDIN_ID: "ali4heydari",
  TWITCH_ID: "ali4heydari",
  BIRTHDATE: new Date(1997, 0, 30),
  CALENDLY_EVENT_LINK: "30min",
  CALENDLY_ID: "ali4heydari",
  CONTACT_EMAIL: "hi@ali4heydari.tech",
  CONTACT_PHONE: "",
  SHORT_NAME: "Ali Heydari's personal website",
  SITE_TITLE: "Ali Heydari",
  SITE_DESCRIPTION: "Ali Heydari's personal website",
  SITE_AUTHOR: "Ali Heydari",
  GITHUB_ID: "ali4heydari",
  GITLAB_ID: "ali4heydari",
  STACK_OVER_FLOW_ID: "8777320/ali4heydari",
  SKYPE_INVITE_ID: "lo1ReeemgPvq",
  SLIDES_ID: "ali4heydari",
  CONTACT_GET_FORM_ID: "b721c787-7978-40ec-9253-5fefaaa6d1e0",
  DISCORD_SERVER_ID: "7Z4Wk2zUuj",
  DISCUSS_SHORTNAME: process.env.NEXT_PUBLIC_DISCUSS_SHORTNAME,
  NODE_ENV: process.env.NODE_ENV,
  RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  HOTJAR_SNIPPET_VERSION: process.env.NEXT_PUBLIC_HOTJAR_SNIPPET_VERSION,
  HOTJAR_ID: process.env.NEXT_PUBLIC_HOTJAR_ID,
};

export default siteConfig;
