const siteConfig = {
  BIRTHDATE: new Date(1997, 0, 30),
  CALENDLY_EVENT_LINK: "30min",
  CALENDLY_ID: "ali4heydari",
  CONTACT_EMAIL: "hi@ali4heydari.tech",
  CONTACT_GET_FORM_ID: "b721c787-7978-40ec-9253-5fefaaa6d1e0",
  CONTACT_PHONE: "",
  DISCORD_SERVER_ID: "7Z4Wk2zUuj",
  DISCUSS_SHORTNAME: process.env.NEXT_PUBLIC_DISCUSS_SHORTNAME,
  FACEBOOK_ID: "",
  GITHUB_ID: "ali4heydari",
  GITLAB_ID: "ali4heydari",
  HOTJAR_ID: process.env.NEXT_PUBLIC_HOTJAR_ID,
  HOTJAR_SNIPPET_VERSION: process.env.NEXT_PUBLIC_HOTJAR_SNIPPET_VERSION,
  INSTAGRAM_ID: "",
  LINKEDIN_ID: "ali4heydari",
  NODE_ENV: process.env.NODE_ENV,
  RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  SENTRY_DSN:
    "https://ed90590a991690c3ba11bada4ffd9aa7@o1022684.ingest.sentry.io/4506293730082816",
  SHORT_NAME: "Ali Heydari's personal website",
  SITE_AUTHOR: "Ali Heydari",
  SITE_DESCRIPTION: "Ali Heydari's personal website",
  SITE_TITLE: "Ali Heydari",
  SKYPE_INVITE_ID: "lo1ReeemgPvq",
  SLIDES_ID: "ali4heydari",
  SPOTIFY_ID: "ali4heydari",
  STACK_OVER_FLOW_ID: "8777320/ali4heydari",
  STEAM_ID: "ali4heydari",
  TWITCH_ID: "ali4heydari",
  TWITTER_ID: "",
};

export default siteConfig;
