export const hardwares = [
  {
    name: "Apple MacBook pro M1 14 inch",
    image: "/static/images/uses/hardware/apple-macbook-pro-m1-14inch.png",
    description: "16GB RAM, 512GB SSD",
  },
  {
    name: "Logitech MX Vertical",
    image: "/static/images/uses/hardware/logitech-mx-vertical.png",
    description: "You wrist will thank you for this 🤌",
  },
  {
    name: "Keychron K3 Mechanical Keyboard V2 (brown switches)",
    image: "/static/images/uses/hardware/keychron-k3.png",
    description: "Unique type experience 🤝",
  },
  {
    name: "Sony WF-1000XM4",
    image: "/static/images/uses/hardware/sony-wf1000xm4.png",
    description: "Excellent noise cancellation 👌",
  },
  {
    name: "Mikrotik hAP ax3",
    image: "/static/images/uses/hardware/mikrotik-hap-ax3.png",
    description: "For bypassing Internet censorship and managing my network",
  },
  {
    name: "TSCO TS2189",
    image: "/static/images/uses/hardware/tsco-ts2189.png",
    description: "Not the best, but it does the job 🦾",
  },
  {
    name: "Asus GL502VY",
    image: "/static/images/uses/hardware/asus-gl502vy.png",
    description: "CPU i7-6700HQ, 16GB RAM, 256GB SSD, 2TB HDD, GTX 980M",
  },
  {
    name: "Logitech G502 Hero",
    image: "/static/images/uses/hardware/logitech-g502-hero.png",
    description: "For gaming",
  },
  {
    name: "Logitech G213",
    image: "/static/images/uses/hardware/logitech-g213.png",
    description: "For gaming",
  },
  {
    name: "Asus VA24EHE",
    image: "/static/images/uses/hardware/asus-va24ehe.png",
    description: "Not the best, but it does the job 🦾",
  },
  {
    name: "LCD arm",
    image: "/static/images/uses/hardware/lcd-arm.png",
    description: "Economical and does the job 🦾",
  },
];

export const softwares = [
  {
    name: "WebStorm",
    image: "/static/images/uses/software/webstorm.png",
    description: "For coding",
    href: "https://www.jetbrains.com/webstorm/",
    tags: ["Coding", "Windows", "MacOS"],
  },
  {
    name: "CleanShot X",
    image: "/static/images/uses/software/cleanshot-x.png",
    description: "For taking screenshots",
    href: "https://cleanshot.com/",
    tags: ["Tool", "MacOS"],
  },
  {
    name: "CleanMyMac X",
    image: "/static/images/uses/software/cleanmymac-x.png",
    description: "For cleaning my Mac",
    href: "https://macpaw.com/cleanmymac",
    tags: ["Tool", "Performance", "MacOS"],
  },
  {
    name: "Raycast",
    image: "/static/images/uses/software/raycast.png",
    description: "For searching and executing commands",
    href: "https://raycast.com/",
    tags: ["Tool", "Coding", "Productivity", "MacOS"],
  },
  {
    name: "AlDente Pro",
    image: "/static/images/uses/software/aldente-pro.png",
    description: "For managing battery health",
    href: "https://aldente.app/",
    tags: ["Tool", "Performance", "MacOS"],
  },
  {
    name: "Rectangle",
    image: "/static/images/uses/software/rectangle.png",
    description: "For managing windows",
    href: "https://rectangleapp.com/",
    tags: ["Tool", "Productivity", "MacOS"],
  },
  {
    name: "WinDirStat",
    image: "/static/images/uses/software/windirstat.png",
    description: "For managing storage",
    href: "https://windirstat.net/",
    tags: ["Tool", "Productivity", "Windows"],
  },
  {
    name: "Everything",
    image: "/static/images/uses/software/everything.png",
    description: "For searching files",
    href: "https://www.voidtools.com/",
    tags: ["Tool", "Windows"],
  },
  {
    name: "SysInternals Suite",
    image: "/static/images/uses/software/sysinternals-suite.png",
    description: "Contains many useful tools to become superuser on Windows",
    href: "https://docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite",
    tags: ["Tool", "Coding", "Windows"],
  },
  {
    name: "NetSetMan",
    image: "/static/images/uses/software/netsetman.png",
    description: "For managing network profiles on Windows",
    href: "https://www.netsetman.com/",
    tags: ["Tool", "Windows"],
  },
  {
    name: "Notion",
    image: "/static/images/uses/software/notion.png",
    description: "For taking notes, and managing my life",
    href: "https://www.notion.so/",
    tags: ["Tool", "Productivity", "Windows", "MacOS"],
  },
  {
    name: "Stremio",
    image: "/static/images/uses/software/stremio.png",
    description: "For watching movies and series",
    href: "https://www.stremio.com/",
    tags: ["Windows", "MacOS", "Linux", "AndroidTV", "DailyUse"],
  },
  {
    name: "Jellyfin",
    image: "/static/images/uses/software/jellyfin.png",
    description: "For watching movies and series",
    href: "https://jellyfin.org/",
    tags: ["Windows", "MacOS", "Linux", "AndroidTV", "DailyUse"],
  },
  {
    name: "Fiddler classic",
    image: "/static/images/uses/software/fiddler-classic.png",
    description: "For debugging HTTP requests",
    href: "https://www.telerik.com/fiddler",
    tags: ["Tool", "Coding", "Windows"],
  },
  {
    name: "Proxifier",
    image: "/static/images/uses/software/proxifier.png",
    description: "For bypassing Internet censorship",
    href: "https://www.proxifier.com/",
    tags: ["Tool", "FilterNet", "Windows"],
  },
  {
    name: "OBS Studio",
    image: "/static/images/uses/software/obs-studio.png",
    description: "For streaming and recording",
    href: "https://obsproject.com/",
    tags: ["Tool", "Windows", "MacOS"],
  },
  {
    name: "Responsively",
    image: "/static/images/uses/software/responsively.png",
    description: "For testing responsive websites",
    href: "https://responsively.app/",
    tags: ["Tool", "Coding", "Windows", "MacOS"],
  },
  {
    name: "InkScape",
    image: "/static/images/uses/software/inkscape.png",
    description: "For vector graphics",
    href: "https://inkscape.org/",
    tags: ["Tool", "Graphic", "Windows", "MacOS"],
  },
  {
    name: "iTerm2",
    image: "/static/images/uses/software/iterm2.png",
    description: "For terminal",
    href: "https://iterm2.com/",
    tags: ["Tool", "Coding", "MacOS"],
  },
  {
    name: "Meld",
    image: "/static/images/uses/software/meld.png",
    description: "For comparing files",
    href: "https://meldmerge.org/",
    tags: ["Tool", "Coding", "Windows", "MacOS"],
  },
  {
    name: "Tabby",
    image: "/static/images/uses/software/tabby.webp",
    description: "For terminal",
    href: "https://tabby.sh/",
    tags: ["Tool", "Coding", "Windows"],
  },
];
