export enum StringKeys {
  ABOUT_US = "about_us",
  ALL_RIGHTS_RESERVED = "all_rights_reserved",
  BE_THE_FIRST_TO_KNOW_ABOUT_THE_NEWS = "be_the_first_to_know_about_the_news",
  CONTACT_US = "contact_us",
  COPYRIGHT = "copyright",
  ENTER_EMAIL_ADDRESS = "enter_email_address",
  GET_STARTED = "get_started",
  SUBSCRIBE = "subscribe",
  SUBSCRIBEING = "subscribeing",
  SUPPORT = "support",
  TERMS = "terms",
  WEBSITE_ADDRESS = "website_address",
  WEBSITE_NAME = "website_name",
}
